from typing import Literal

head_items = {
    'mage cowl': 'https://render.albiononline.com/v1/item/T8_HEAD_CLOTH_SET3@0.png',
    'scholar cowl': 'https://render.albiononline.com/v1/item/T8_HEAD_CLOTH_SET1@0.png',
    'cleric cowl': 'https://render.albiononline.com/v1/item/T8_HEAD_CLOTH_SET2@0.png',
    'royal cowl': 'https://render.albiononline.com/v1/item/T8_HEAD_CLOTH_ROYAL@0.png',
    'druid cowl': 'https://render.albiononline.com/v1/item/T8_HEAD_CLOTH_KEEPER@0.png',
    'fiend cowl': 'https://render.albiononline.com/v1/item/T8_HEAD_CLOTH_HELL@0.png',
    'cultist cowl': 'https://render.albiononline.com/v1/item/T8_HEAD_CLOTH_MORGANA@0.png',
    'feyscale hat': 'https://render.albiononline.com/v1/item/T8_HEAD_CLOTH_FEY@0.png',
    'cowl of purity': 'https://render.albiononline.com/v1/item/T8_HEAD_CLOTH_AVALON@0.png',
    'mercenary hood': 'https://render.albiononline.com/v1/item/T8_HEAD_LEATHER_SET1@0.png',
    'hunter hood': 'https://render.albiononline.com/v1/item/T8_HEAD_LEATHER_SET2@0.png',
    'assassin hood': 'https://render.albiononline.com/v1/item/T8_HEAD_LEATHER_SET3@0.png',
    'royal hood': 'https://render.albiononline.com/v1/item/T8_HEAD_LEATHER_ROYAL@0.png',
    'stalker hood': 'https://render.albiononline.com/v1/item/T8_HEAD_LEATHER_MORGANA@0.png',
    'hellion hood': 'https://render.albiononline.com/v1/item/T8_HEAD_LEATHER_HELL@0.png',
    'specter hood': 'https://render.albiononline.com/v1/item/T8_HEAD_LEATHER_UNDEAD@0.png',
    'mistwalker hood': 'https://render.albiononline.com/v1/item/T8_HEAD_LEATHER_FEY@0.png',
    'hood of tenacity': 'https://render.albiononline.com/v1/item/T8_HEAD_LEATHER_AVALON@0.png',
    'soldier helmet': 'https://render.albiononline.com/v1/item/T8_HEAD_PLATE_SET1@0.png',
    'knight helmet': 'https://render.albiononline.com/v1/item/T8_HEAD_PLATE_SET2@0.png',
    'guardian helmet': 'https://render.albiononline.com/v1/item/T8_HEAD_PLATE_SET3@0.png',
    'royal helmet': 'https://render.albiononline.com/v1/item/T8_HEAD_PLATE_ROYAL@0.png',
    'graveguard helmet': 'https://render.albiononline.com/v1/item/T8_HEAD_PLATE_UNDEAD@0.png',
    'demon helmet': 'https://render.albiononline.com/v1/item/T8_HEAD_PLATE_HELL@0.png',
    'judicator helmet': 'https://render.albiononline.com/v1/item/T8_HEAD_PLATE_KEEPER@0.png',
    'duskweaver helmet': 'https://render.albiononline.com/v1/item/T8_HEAD_PLATE_FEY@0.png',
    'helmet of valor': 'https://render.albiononline.com/v1/item/T8_HEAD_PLATE_AVALON@0.png',
}


body_items = {
    'mage robe': 'https://render.albiononline.com/v1/item/T8_ARMOR_CLOTH_SET3@0.png',
    'scholar robe': 'https://render.albiononline.com/v1/item/T8_ARMOR_CLOTH_SET1@0.png',
    'cleric robe': 'https://render.albiononline.com/v1/item/T8_ARMOR_CLOTH_SET2@0.png',
    'royal robe': 'https://render.albiononline.com/v1/item/T8_ARMOR_CLOTH_ROYAL@0.png',
    'druid robe': 'https://render.albiononline.com/v1/item/T8_ARMOR_CLOTH_KEEPER@0.png',
    'fiend robe': 'https://render.albiononline.com/v1/item/T8_ARMOR_CLOTH_HELL@0.png',
    'cultist robe': 'https://render.albiononline.com/v1/item/T8_ARMOR_CLOTH_MORGANA@0.png',
    'feyscale robe': 'https://render.albiononline.com/v1/item/T8_ARMOR_CLOTH_FEY@0.png',
    'robe of purity': 'https://render.albiononline.com/v1/item/T8_ARMOR_CLOTH_AVALON@0.png',
    'mercenary jacket': 'https://render.albiononline.com/v1/item/T8_ARMOR_LEATHER_SET1@0.png',
    'hunter jacket': 'https://render.albiononline.com/v1/item/T8_ARMOR_LEATHER_SET2@0.png',
    'assassin jacket': 'https://render.albiononline.com/v1/item/T8_ARMOR_LEATHER_SET3@0.png',
    'royal jacket': 'https://render.albiononline.com/v1/item/T8_ARMOR_LEATHER_ROYAL@0.png',
    'stalker jacket': 'https://render.albiononline.com/v1/item/T8_ARMOR_LEATHER_MORGANA@0.png',
    'hellion jacket': 'https://render.albiononline.com/v1/item/T8_ARMOR_LEATHER_HELL@0.png',
    'specter jacket': 'https://render.albiononline.com/v1/item/T8_ARMOR_LEATHER_UNDEAD@0.png',
    'mistwalker jacket': 'https://render.albiononline.com/v1/item/T8_ARMOR_LEATHER_FEY@0.png',
    'jacket of tenacity': 'https://render.albiononline.com/v1/item/T8_ARMOR_LEATHER_AVALON@0.png',
    'soldier armor': 'https://render.albiononline.com/v1/item/T8_ARMOR_PLATE_SET1@0.png',
    'knight armor': 'https://render.albiononline.com/v1/item/T8_ARMOR_PLATE_SET2@0.png',
    'guardian armor': 'https://render.albiononline.com/v1/item/T8_ARMOR_PLATE_SET3@0.png',
    'royal armor': 'https://render.albiononline.com/v1/item/T8_ARMOR_PLATE_ROYAL@0.png',
    'graveguard armor': 'https://render.albiononline.com/v1/item/T8_ARMOR_PLATE_UNDEAD@0.png',
    'demon armor': 'https://render.albiononline.com/v1/item/T8_ARMOR_PLATE_HELL@0.png',
    'judicator armor': 'https://render.albiononline.com/v1/item/T8_ARMOR_PLATE_KEEPER@0.png',
    'duskweaver armor': 'https://render.albiononline.com/v1/item/T8_ARMOR_PLATE_FEY@0.png',
    'armor of valor': 'https://render.albiononline.com/v1/item/T8_ARMOR_PLATE_AVALON@0.png',
}

feet_items = {
    'mage sandals': 'https://render.albiononline.com/v1/item/T8_SHOES_CLOTH_SET3@0.png',
    'scholar sandals': 'https://render.albiononline.com/v1/item/T8_SHOES_CLOTH_SET1@0.png',
    'cleric sandals': 'https://render.albiononline.com/v1/item/T8_SHOES_CLOTH_SET2@0.png',
    'royal sandals': 'https://render.albiononline.com/v1/item/T8_SHOES_CLOTH_ROYAL@0.png',
    'druid sandals': 'https://render.albiononline.com/v1/item/T8_SHOES_CLOTH_KEEPER@0.png',
    'fiend sandals': 'https://render.albiononline.com/v1/item/T8_SHOES_CLOTH_HELL@0.png',
    'cultist sandals': 'https://render.albiononline.com/v1/item/T8_SHOES_CLOTH_MORGANA@0.png',
    'feyscale sandals': 'https://render.albiononline.com/v1/item/T8_SHOES_CLOTH_FEY@0.png',
    'sandals of purity': 'https://render.albiononline.com/v1/item/T8_SHOES_CLOTH_AVALON@0.png',
    'mercenary shoes': 'https://render.albiononline.com/v1/item/T8_SHOES_LEATHER_SET1@0.png',
    'hunter shoes': 'https://render.albiononline.com/v1/item/T8_SHOES_LEATHER_SET2@0.png',
    'assassin shoes': 'https://render.albiononline.com/v1/item/T8_SHOES_LEATHER_SET3@0.png',
    'royal shoes': 'https://render.albiononline.com/v1/item/T8_SHOES_LEATHER_ROYAL@0.png',
    'stalker shoes': 'https://render.albiononline.com/v1/item/T8_SHOES_LEATHER_MORGANA@0.png',
    'hellion shoes': 'https://render.albiononline.com/v1/item/T8_SHOES_LEATHER_HELL@0.png',
    'specter shoes': 'https://render.albiononline.com/v1/item/T8_SHOES_LEATHER_UNDEAD@0.png',
    'mistwalker shoes': 'https://render.albiononline.com/v1/item/T8_SHOES_LEATHER_FEY@0.png',
    'shoes of tenacity': 'https://render.albiononline.com/v1/item/T8_SHOES_LEATHER_AVALON@0.png',
    'soldier boots': 'https://render.albiononline.com/v1/item/T8_SHOES_PLATE_SET1@0.png',
    'knight boots': 'https://render.albiononline.com/v1/item/T8_SHOES_PLATE_SET2@0.png',
    'guardian boots': 'https://render.albiononline.com/v1/item/T8_SHOES_PLATE_SET3@0.png',
    'royal boots': 'https://render.albiononline.com/v1/item/T8_SHOES_PLATE_ROYAL@0.png',
    'graveguard boots': 'https://render.albiononline.com/v1/item/T8_SHOES_PLATE_UNDEAD@0.png',
    'demon boots': 'https://render.albiononline.com/v1/item/T8_SHOES_PLATE_HELL@0.png',
    'judicator boots': 'https://render.albiononline.com/v1/item/T8_SHOES_PLATE_KEEPER@0.png',
    'duskweaver boots': 'https://render.albiononline.com/v1/item/T8_SHOES_PLATE_FEY@0.png',
    'boots of valor': 'https://render.albiononline.com/v1/item/T8_SHOES_PLATE_AVALON@0.png',
}

weapons = {
    'curse staff': 'https://render.albiononline.com/v1/item/T8_MAIN_CURSEDSTAFF@0.png',
    'great curse staff': 'https://render.albiononline.com/v1/item/T8_2H_CURSEDSTAFF@0.png',
    'demonic staff': 'https://render.albiononline.com/v1/item/T8_2H_DEMONICSTAFF@0.png',
    'lifecurse staff': 'https://render.albiononline.com/v1/item/T8_MAIN_CURSEDSTAFF_UNDEAD@0.png',
    'cursed skull': 'https://render.albiononline.com/v1/item/T8_2H_SKULLORB_HELL@0.png',
    'damnation staff': 'https://render.albiononline.com/v1/item/T8_2H_CURSEDSTAFF_MORGANA@0.png',
    'shadowcaller': 'https://render.albiononline.com/v1/item/T8_MAIN_CURSEDSTAFF_AVALON@0.png',
    'frost staff': 'https://render.albiononline.com/v1/item/T8_MAIN_FROSTSTAFF@0.png',
    'great frost staff': 'https://render.albiononline.com/v1/item/T8_2H_FROSTSTAFF@0.png',
    'glacial staff': 'https://render.albiononline.com/v1/item/T8_2H_GLACIALSTAFF@0.png',
    'hoarfrost staff': 'https://render.albiononline.com/v1/item/T8_MAIN_FROSTSTAFF_KEEPER@0.png',
    'icicle staff': 'https://render.albiononline.com/v1/item/T8_2H_ICEGAUNTLETS_HELL@0.png',
    'permafrost prism': 'https://render.albiononline.com/v1/item/T8_2H_ICECRYSTAL_UNDEAD@0.png',
    'chillhowl': 'https://render.albiononline.com/v1/item/T8_MAIN_FROSTSTAFF_AVALON@0.png',
    'arcane staff': 'https://render.albiononline.com/v1/item/T8_MAIN_ARCANESTAFF@0.png',
    'great arcane staff': 'https://render.albiononline.com/v1/item/T8_2H_ARCANESTAFF@0.png',
    'enigmatic staff': 'https://render.albiononline.com/v1/item/T8_2H_ENIGMATICSTAFF@0.png',
    'witchwork staff': 'https://render.albiononline.com/v1/item/T8_MAIN_ARCANESTAFF_UNDEAD@0.png',
    'occult staff': 'https://render.albiononline.com/v1/item/T8_2H_ARCANESTAFF_HELL@0.png',
    'malevolent locus': 'https://render.albiononline.com/v1/item/T8_2H_ENIGMATICORB_MORGANA@0.png',
    'evensong': 'https://render.albiononline.com/v1/item/T8_2H_ARCANE_RINGPAIR_AVALON@0.png',
    'holy staff': 'https://render.albiononline.com/v1/item/T8_MAIN_HOLYSTAFF@0.png',
    'great holy staff': 'https://render.albiononline.com/v1/item/T8_2H_HOLYSTAFF@0.png',
    'divine staff': 'https://render.albiononline.com/v1/item/T8_2H_DIVINESTAFF@0.png',
    'lifetouch staff': 'https://render.albiononline.com/v1/item/T8_MAIN_HOLYSTAFF_MORGANA@0.png',
    'fallen staff': 'https://render.albiononline.com/v1/item/T8_2H_HOLYSTAFF_HELL@0.png',
    'redemption staff': 'https://render.albiononline.com/v1/item/T8_2H_HOLYSTAFF_UNDEAD@0.png',
    'hallowfall': 'https://render.albiononline.com/v1/item/T8_MAIN_HOLYSTAFF_AVALON@0.png',
    'fire staff': 'https://render.albiononline.com/v1/item/T8_MAIN_FIRESTAFF@0.png',
    'great fire staff': 'https://render.albiononline.com/v1/item/T8_2H_FIRESTAFF@0.png',
    'infernal staff': 'https://render.albiononline.com/v1/item/T8_2H_INFERNOSTAFF@0.png',
    'wildfire staff': 'https://render.albiononline.com/v1/item/T8_MAIN_FIRESTAFF_KEEPER@0.png',
    'brimstone staff': 'https://render.albiononline.com/v1/item/T8_2H_FIRESTAFF_HELL@0.png',
    'blazing staff': 'https://render.albiononline.com/v1/item/T8_2H_INFERNOSTAFF_MORGANA@0.png',
    'dawnsong': 'https://render.albiononline.com/v1/item/T8_2H_FIRE_RINGPAIR_AVALON@0.png',
    'quarterstaff': 'https://render.albiononline.com/v1/item/T8_2H_QUARTERSTAFF@0.png',
    'ironclad staff': 'https://render.albiononline.com/v1/item/T8_2H_IRONCLADEDSTAFF@0.png',
    'double-bladed staff': 'https://render.albiononline.com/v1/item/T8_2H_DOUBLEBLADEDSTAFF@0.png',
    'black monk stave': 'https://render.albiononline.com/v1/item/T8_2H_COMBATSTAFF_MORGANA@0.png',
    'soulscythe': 'https://render.albiononline.com/v1/item/T8_2H_TWINSCYTHE_HELL@0.png',
    'staff of balance': 'https://render.albiononline.com/v1/item/T8_2H_ROCKSTAFF_KEEPER@0.png',
    'grailseeker': 'https://render.albiononline.com/v1/item/T8_2H_QUARTERSTAFF_AVALON@0.png',
    'dagger': 'https://render.albiononline.com/v1/item/T8_MAIN_DAGGER@0.png',
    'dagger pair': 'https://render.albiononline.com/v1/item/T8_2H_DAGGERPAIR@0.png',
    'claws': 'https://render.albiononline.com/v1/item/T8_2H_CLAWPAIR@0.png',
    'bloodletter': 'https://render.albiononline.com/v1/item/T8_MAIN_RAPIER_MORGANA@0.png',
    'demonfang': 'https://render.albiononline.com/v1/item/T8_MAIN_DAGGER_HELL@0.png',
    'deathgivers': 'https://render.albiononline.com/v1/item/T8_2H_DUALSICKLE_UNDEAD@0.png',
    'bridled fury': 'https://render.albiononline.com/v1/item/T8_2H_DAGGER_KATAR_AVALON@0.png',
    'nature staff': 'https://render.albiononline.com/v1/item/T8_MAIN_NATURESTAFF@0.png',
    'great nature staff': 'https://render.albiononline.com/v1/item/T8_2H_NATURESTAFF@0.png',
    'druidic staff': 'https://render.albiononline.com/v1/item/T8_MAIN_NATURESTAFF_KEEPER@0.png',
    'blight staff': 'https://render.albiononline.com/v1/item/T8_2H_NATURESTAFF_HELL@0.png',
    'rampant staff': 'https://render.albiononline.com/v1/item/T8_2H_NATURESTAFF_KEEPER@0.png',
    'ironroot staff': 'https://render.albiononline.com/v1/item/T8_MAIN_NATURESTAFF_AVALON@0.png',
    'spear': 'https://render.albiononline.com/v1/item/T8_MAIN_SPEAR@0.png',
    'pike': 'https://render.albiononline.com/v1/item/T8_2H_SPEAR@0.png',
    'glaive': 'https://render.albiononline.com/v1/item/T8_2H_GLAIVE@0.png',
    'heron spear': 'https://render.albiononline.com/v1/item/T8_MAIN_SPEAR_KEEPER@0.png',
    'spirit hunter': 'https://render.albiononline.com/v1/item/T8_2H_HARPOON_HELL@0.png',
    'trinity spear': 'https://render.albiononline.com/v1/item/T8_2H_TRIDENT_UNDEAD@0.png',
    'daybreaker': 'https://render.albiononline.com/v1/item/T8_MAIN_SPEAR_LANCE_AVALON@0.png',
    'bow': 'https://render.albiononline.com/v1/item/T8_2H_BOW@0.png',
    'warbow': 'https://render.albiononline.com/v1/item/T8_2H_WARBOW@0.png',
    'longbow': 'https://render.albiononline.com/v1/item/T8_2H_LONGBOW@0.png',
    'whispering bow': 'https://render.albiononline.com/v1/item/T8_2H_LONGBOW_UNDEAD@0.png',
    'wailing bow': 'https://render.albiononline.com/v1/item/T8_2H_BOW_HELL@0.png',
    'bow of badon': 'https://render.albiononline.com/v1/item/T8_2H_BOW_KEEPER@0.png',
    'mistpiercer': 'https://render.albiononline.com/v1/item/T8_2H_BOW_AVALON@0.png',
    'crossbow': 'https://render.albiononline.com/v1/item/T8_2H_CROSSBOW@0.png',
    'light crossbow': 'https://render.albiononline.com/v1/item/T8_MAIN_1HCROSSBOW@0.png',
    'heavy crossbow': 'https://render.albiononline.com/v1/item/T8_2H_CROSSBOWLARGE@0.png',
    'weeping repeater': 'https://render.albiononline.com/v1/item/T8_2H_REPEATINGCROSSBOW_UNDEAD@0.png',
    'boltcasters': 'https://render.albiononline.com/v1/item/T8_2H_DUALCROSSBOW_HELL@0.png',
    'siegebow': 'https://render.albiononline.com/v1/item/T8_2H_CROSSBOWLARGE_MORGANA@0.png',
    'energy shaper': 'https://render.albiononline.com/v1/item/T8_2H_CROSSBOW_CANNON_AVALON@0.png',
    'brawler gloves': 'https://render.albiononline.com/v1/item/T8_2H_KNUCKLES_SET1@0.png',
    'battle bracers': 'https://render.albiononline.com/v1/item/T8_2H_KNUCKLES_SET2@0.png',
    'spiked gauntlets': 'https://render.albiononline.com/v1/item/T8_2H_KNUCKLES_SET3@0.png',
    'ursine maulers': 'https://render.albiononline.com/v1/item/T8_2H_KNUCKLES_KEEPER@0.png',
    'hellfire hands': 'https://render.albiononline.com/v1/item/T8_2H_KNUCKLES_HELL@0.png',
    'revenstrike cestus': 'https://render.albiononline.com/v1/item/T8_2H_KNUCKLES_MORGANA@0.png',
    'fists of avalon': 'https://render.albiononline.com/v1/item/T8_2H_KNUCKLES_AVALON@0.png',
    'hammer': 'https://render.albiononline.com/v1/item/T8_MAIN_HAMMER@0.png',
    'polehammer': 'https://render.albiononline.com/v1/item/T8_2H_POLEHAMMER@0.png',
    'great hammer': 'https://render.albiononline.com/v1/item/T8_2H_HAMMER@0.png',
    'tombhammer': 'https://render.albiononline.com/v1/item/T8_2H_HAMMER_UNDEAD@0.png',
    'forge hammers': 'https://render.albiononline.com/v1/item/T8_2H_DUALHAMMER_HELL@0.png',
    'grovekeeper': 'https://render.albiononline.com/v1/item/T8_2H_RAM_KEEPER@0.png',
    'hand of justice': 'https://render.albiononline.com/v1/item/T8_2H_HAMMER_AVALON@0.png',
    'mace': 'https://render.albiononline.com/v1/item/T8_MAIN_MACE@0.png',
    'morningstar': 'https://render.albiononline.com/v1/item/T8_2H_FLAIL@0.png',
    'bedrock mace': 'https://render.albiononline.com/v1/item/T8_MAIN_ROCKMACE_KEEPER@0.png',
    'incubus mace': 'https://render.albiononline.com/v1/item/T8_MAIN_MACE_HELL@0.png',
    'camlann mace': 'https://render.albiononline.com/v1/item/T8_2H_MACE_MORGANA@0.png',
    'oathkeepers': 'https://render.albiononline.com/v1/item/T8_2H_DUALMACE_AVALON@0.png',
    'battleaxe': 'https://render.albiononline.com/v1/item/T8_MAIN_AXE@0.png',
    'greataxe': 'https://render.albiononline.com/v1/item/T8_2H_AXE@0.png',
    'halberd': 'https://render.albiononline.com/v1/item/T8_2H_HALBERD@0.png',
    'carrioncaller': 'https://render.albiononline.com/v1/item/T8_2H_HALBERD_MORGANA@0.png',
    'infernal scythe': 'https://render.albiononline.com/v1/item/T8_2H_SCYTHE_HELL@0.png',
    'bear paws': 'https://render.albiononline.com/v1/item/T8_2H_DUALAXE_KEEPER@0.png',
    'realmbreaker': 'https://render.albiononline.com/v1/item/T8_2H_AXE_AVALON@0.png',
    'broadsword': 'https://render.albiononline.com/v1/item/T8_MAIN_SWORD@0.png',
    'claymore': 'https://render.albiononline.com/v1/item/T8_2H_CLAYMORE@0.png',
    'dual swords': 'https://render.albiononline.com/v1/item/T8_2H_DUALSWORD@0.png',
    'carving sword': 'https://render.albiononline.com/v1/item/T8_2H_CLEAVER_HELL@0.png',
    'clarent blade': 'https://render.albiononline.com/v1/item/T8_MAIN_SCIMITAR_MORGANA@0.png',
    'galatine pair': 'https://render.albiononline.com/v1/item/T8_2H_DUALSCIMITAR_UNDEAD@0.png',
    'kingmaker': 'https://render.albiononline.com/v1/item/T8_2H_CLAYMORE_AVALON@0.png'
}

offhands = {
    'tome': 'https://render.albiononline.com/v1/item/T8_OFF_BOOK@0.png',
    'eye of secrets': 'https://render.albiononline.com/v1/item/T8_OFF_ORB_MORGANA@0.png',
    'muisak': 'https://render.albiononline.com/v1/item/T8_OFF_DEMONSKULL_HELL@0.png',
    'taproot': 'https://render.albiononline.com/v1/item/T8_OFF_TOTEM_KEEPER@0.png',
    'celestial censer': 'https://render.albiononline.com/v1/item/T8_OFF_CENSER_AVALON@0.png',
    'torch': 'https://render.albiononline.com/v1/item/T8_OFF_TORCH@0.png',
    'mistcaller': 'https://render.albiononline.com/v1/item/T8_OFF_HORN_KEEPER@0.png',
    'leering cane': 'https://render.albiononline.com/v1/item/T8_OFF_JESTERCANE_HELL@0.png',
    'cryptcandle': 'https://render.albiononline.com/v1/item/T8_OFF_LAMP_UNDEAD@0.png',
    'sacred scepter': 'https://render.albiononline.com/v1/item/T8_OFF_TALISMAN_AVALON@0.png',
    'shield': 'https://render.albiononline.com/v1/item/T8_OFF_SHIELD@0.png',
    'sarcophagus': 'https://render.albiononline.com/v1/item/T8_OFF_TOWERSHIELD_UNDEAD@0.png',
    'caitiff': 'https://render.albiononline.com/v1/item/T8_OFF_SHIELD_HELL@0.png',
    'facebreaker': 'https://render.albiononline.com/v1/item/T8_OFF_SPIKEDSHIELD_MORGANA@0.png',
    'astral aegis': 'https://render.albiononline.com/v1/item/T8_OFF_SHIELD_AVALON@0.png',
}

# LITERAL DEFINITIONS 
head_items_literal = [
    'mage cowl',
    'scholar cowl',
    'cleric cowl',
    'royal cowl',
    'druid cowl',
    'fiend cowl',
    'cultist cowl',
    'feyscale hat',
    'cowl of purity',
    'mercenary hood',
    'hunter hood',
    'assassin hood',
    'royal hood',
    'stalker hood',
    'hellion hood',
    'specter hood',
    'mistwalker hood',
    'hood of tenacity',
    'soldier helmet',
    'knight helmet',
    'guardian helmet',
    'royal helmet',
    'graveguard helmet',
    'demon helmet',
    'judicator helmet',
    'duskweaver helmet',
    'helmet of valor',
]


body_items_literal = Literal[
    'mage robe',
    'scholar robe',
    'cleric robe',
    'royal robe',
    'druid robe',
    'fiend robe',
    'cultist robe',
    'feyscale robe',
    'robe of purity',
    'mercenary jacket',
    'hunter jacket',
    'assassin jacket',
    'royal jacket',
    'stalker jacket',
    'hellion jacket',
    'specter jacket',
    'mistwalker jacket',
    'jacket of tenacity',
    'soldier armor',
    'knight armor',
    'guardian armor',
    'royal armor',
    'graveguard armor',
    'demon armor',
    'judicator armor',
    'duskweaver armor',
    'armor of valor',
]

feet_items_literal = Literal[
    'mage sandals',
    'scholar sandals',
    'cleric sandals',
    'royal sandals',
    'druid sandals',
    'fiend sandals',
    'cultist sandals',
    'feyscale sandals',
    'sandals of purity',
    'mercenary shoes',
    'hunter shoes',
    'assassin shoes',
    'royal shoes',
    'stalker shoes',
    'hellion shoes',
    'specter shoes',
    'mistwalker shoes',
    'shoes of tenacity',
    'soldier boots',
    'knight boots',
    'guardian boots',
    'royal boots',
    'graveguard boots',
    'demon boots',
    'judicator boots',
    'duskweaver boots',
    'boots of valor',
]

weapons_literal = Literal[
    'curse staff',
    'great curse staff',
    'demonic staff',
    'lifecurse staff',
    'cursed skull',
    'damnation staff',
    'shadowcaller',
    'frost staff',
    'great frost staff',
    'glacial staff',
    'hoarfrost staff',
    'icicle staff',
    'permafrost prism',
    'chillhowl',
    'arcane staff',
    'great arcane staff',
    'enigmatic staff',
    'witchwork staff',
    'occult staff',
    'malevolent locus',
    'evensong',
    'holy staff',
    'great holy staff',
    'divine staff',
    'lifetouch staff',
    'fallen staff',
    'redemption staff',
    'hallowfall',
    'fire staff',
    'great fire staff',
    'infernal staff',
    'infernal staff',
    'wildfire staff',
    'brimstone staff',
    'blazing staff',
    'dawnsong',
    'quarterstaff',
    'ironclad staff',
    'double-bladed staff',
    'black monk stave',
    'soulscythe',
    'staff of balance',
    'grailseeker',
    'dagger',
    'dagger pair',
    'claws',
    'bloodletter',
    'demonfang',
    'deathgivers',
    'bridled fury',
    'nature staff',
    'great nature staff',
    'druidic staff',
    'blight staff',
    'rampant staff',
    'ironroot staff',
    'spear',
    'pike',
    'glaive',
    'heron spear',
    'spirit hunter',
    'trinity spear',
    'daybreaker',
    'bow',
    'warbow',
    'longbow',
    'whispering bow',
    'wailing bow',
    'bow of badon',
    'mistpiercer',
    'crossbow',
    'light crossbow',
    'heavy crossbow',
    'weeping repeater',
    'boltcasters',
    'siegebow',
    'energy shaper',
    'brawler gloves',
    'battle bracers',
    'spiked gauntlets',
    'ursine maulers',
    'hellfire hands',
    'revenstrike cestus',
    'fists of avalon',
    'hammer',
    'polehammer',
    'great hammer',
    'tombhammer',
    'forge hammers',
    'grovekeeper',
    'hand of justice',
    'mace',
    'morningstar',
    'bedrock mace',
    'incubus mace',
    'camlann mace',
    'oathkeepers',
    'battleaxe',
    'greataxe',
    'halberd',
    'carrioncaller',
    'infernal scythe',
    'bear paws',
    'realmbreaker',
    'broadsword',
    'claymore',
    'dual swords',
    'carving sword',
    'clarent blade',
    'galatine pair',
    'kingmaker',
]

offhands_literal = Literal[
    'tome',
    'eye of secrets',
    'muisak',
    'taproot',
    'celestial censer',
    'torch',
    'mistcaller',
    'leering cane',
    'cryptcandle',
    'sacred scepter',
    'shield',
    'sarcophagus',
    'caitiff',
    'facebreaker',
    'astral aegis',
]